### ISSUE TITLE
메뉴 수정시 벨리데이션에 대한 문제

### ISSUE THREAD

**Issue by ces518** [hmterestingthinking/Honeybread#20]
## 이슈 
- 메뉴 등록시에는 기존에 등록된 엔티티가 없기 때문에 큰 문제가 없지만 수정시에 하나 이슈가 있음
- 기존에 등록된 optionGroup 과, option 들의 존재 유무까지 검증할 것인가?... (검증을 위한 쿼리가 발생)
- 아니면 수정시에는 기존 optionGroup과 option들의 존재여부를 무시하고, 매번 새롭게 엎어치는 방식 (이럴 경우에는 히스토리를 따로 남기는게 좋을듯)
- 어떤식으로 방향을 잡으면 좋을지 고민이네요   (ఠ ̥̆ ఠ) 

`메뉴 수정 Request Example`

```json
{
   "storeId": "1",
   "menuGroupId":"1",
   "categoryId":"1",
   "name":"간장 찜닭",
   "description":"존맛탱 간장 찜닭",
   "basicPrice":{
      "value":"10000"
   },
   "optionGroups":[
      {
         "id": "1",
         "name":"맛 선택",
         "type":"BASIC",
         "minimumSelectCount":"1",
         "maximumSelectCount":"1",
         "options":[
            {
               "id": "1",
               "name":"순한맛",
               "price":{
                  "value":"0"
               }
            },
            {
               "id": "2",
               "name":"약간 매운맛",
               "price":{
                  "value":"0"
               }
            },
            {
               "id": "3",
               "name":"매운맛",
               "price":{
                  "value":"0"
               }
            }
         ]
      }
   ],
   "main":true,
   "best":true
}
```

**Comment by leaf-777** [comment]
저는 지금 이 이슈를 이렇게 이해하고 있는데 일단 이 내용이 맞는지부터 확인 부탁드릴게요

1. optionsGroups(또는 options)에 1, 2가 등록되어있었다
2. 수정 시 opriont_group_id 1의 정보만 넘겼다

-> 기존 데이터인 2를 조회해서 벨리데이션 및 기타 처리를 해줄 것이냐
-> 아니면 수정요청한 optionGroups으로 엎어칠 것이냐

맞나요?..

**Comment by leaf-777** [comment]
만약 이해한바가 맞다면 엎어치는 게 맞다고 생각해요~
요청을 PUT으로만 받으면 되는 거라고 생각합니다 :)..

추후에 뭐 기존 데이터를 조회해서 처리해야 하는 로직이 있다면 그 땐 PATCH 요청을 추가하고,
패치 관련 로직을 만들면 되지 않을까요?!

**Comment by ces518** [comment]
1. optionsGroups(또는 options)에 1, 2가 등록되어있었다
2. 수정 시 opriont_group_id 1, 2의 정보와 새로운 옵션 (entity id 가 없음) 넘겼다
-> 기존 데이터인 1, 2를 조회해서 정말 존재하는 옵션 아이디인지 검증을 해야할까 ?
-> 아니면 수정요청한 optionGroups으로 엎어칠 것이냐

**Comment by leaf-777** [comment]
상황에 따라 다르겠지만 일단 이 메뉴 도메인?에서는 엎어치는 게 맞아보여요
굳이 기존 것을 조회해서 검증하면서 처리할 필요가 딱히 없어보이서요
