### ISSUE TITLE
주소 정보 관련 db 스키마에 대한 궁금증(?)

### ISSUE THREAD

**Issue by leaf-777** [hmterestingthinking/Honeybread#23]
db에 주소 정보를 어떻게 담아야할지 모르겠네요..

주소 관련 정보가 쓰이는 곳을 좀 보면
- 스토어의 실제 위치
- 스토어가 배달이 가능한 지점들
- 유저 주소
- :

스토어의 실제위치와 유저 주소의 경우 상세한 주소까지 있어야 되는거고
배달가능지점은 동?까지만 있어도 되는 것 같은데..

이제 db에 넣을 때 어떻게 넣어야 할지 잘 모르겠네요..
예를들면..

1. 우편번호 방식으로 저장한다.
스토어의 실제위치, 유저 주소의 경우 우편번호와 번지수, 상세주소를 입력한다
배달가능지점은 우편번호만 저장한다

2. 일일히 텍스트로 저장한다.
si
gu
dong
bunji
:

등등 방식이 여러개가 있을 텐데..
어떤 단위로, 어떤 방식으로 저장해야 할지 얘기를 해보면 좋을 것 같습니다..

**Comment by sup2is** [comment]
![화면 캡처 2021-03-28 102405](https://user-images.githubusercontent.com/30790184/112739508-d6c1b580-8faf-11eb-81c0-c4e1a4447911.png)

저는 검색을 ES를 통해서 하기 때문에 user의 최근사용주소를 위와 같이 설계했었는데요

스토어입장에서 생각해보면

1. 배달원들에게 제공할 가게 위치
2. 전시에서 사용자에게 보여줄 가게 위치
3. 검색가능한 가게 위치

정도가 있을것같은데
이것도 si, gu, dong으로 나누기보단 위 방식대로 저장하는게 어떨까 싶네요~~!

**Comment by leaf-777** [comment]
@sup2is 현섭님~ 몇가지 질문이 있습니다 :)

1.
스토어 입장에서 배달원들에게 제공할 가게 위치와 전시에서 사용자에게 보여줄 가게 위치가 있다고 하셨는데용
하나만 있어도 될 것 같은데 분리되어있는 이유가 어떤건가용..? 👀

2.
'검색가능한 가게 위치' -> 따로 스토어가 검색 가능한 가게 위치를 설정해야 하나요?
아니면.. '검색가능한 가게 위치'라는 걸 '배달가능 주소'(동까지)라고 봐도 되는건지

3.
저번 회의에서 주소 체계를 전문으로 박기로 한 게 생각났네요
우리 스토어 위치정보 필드에는 그럼 '경기도 성남시 판교동 판교로 12번길 34-5 11층' 이런식으로 저장되어있는건가요?

**Comment by sup2is** [comment]
1.
아.. 전달에 조금 오류가 있었네요.. `배달원들에게 제공할 가게 위치`, `전시에서 사용자에게 보여줄 가게 위치`는 말씀하신것처럼 하나만 있는거고 굳이 사례로 분류해서 저렇게 표현했습니다. **결론적으로는 서로 같음!**

2.
이것도 마찬가지로 `검색가능한 가게 위치` == `배달가능 주소` 라고 생각하시면 될 것 같고 스토어가 검색 가능한 위치를 설정하는게 맞는것같습니다~ 

3.
네 전시에 보여줄 스토어 위치 정보 필드는 말씀하신대로 `경기도 성남시 판교동 판교로 12번길 34-5 11층` 가 맞는것 같습니다!

**Comment by leaf-777** [comment]
@sup2is
네네 감사합니다 현섭님
고롷게 저도 진행할게용~
