### ISSUE TITLE
store 설계 검토요청 v1.0.0

### ISSUE THREAD

**Issue by leaf-777** [hmterestingthinking/Honeybread#7]
어제 회의 후에 03/20(토)
운영시간 관련해서 수정해야 할 사항들과 추가로 정해야할 정책들 조금 반영해서 erd 그려봤는데
여유 있으실 때 코멘트 부탁드릴게요~
한번에 뙇! 하는 것보단 자주 공유하고 피드백받아서 만들어가는 게 좋을 것 같아서 :)
확인 부탁드려요~
https://dbdiagram.io/d/604d716afcdcb6230b24067d
(필드에 마우스 호버하면 상세설명 나오니까 보실 때 참고하세요~)

**Comment by leaf-777** [comment]
링크에서 보기 힘드실 수 있으니까 따로 올려볼게요 👀
![스토어_v1 0 0](https://user-images.githubusercontent.com/76275595/111895722-cb263a00-8a57-11eb-80c5-a944620ab9b4.png)

[스토어_v1.0.0.zip](https://github.com/hmterestingthinking/Honeybread/files/6176931/_v1.0.0.zip)

**Comment by ces518** [comment]
LGTM

**Comment by sup2is** [comment]
Gooooood~!

**Comment by leaf-777** [comment]
브랜드는 우리 플젝에 단순 crud만 늘어날 것 같아서 우리 플젝에는 아웃시킬게요~
![스토어_v1 1 0](https://user-images.githubusercontent.com/76275595/111897947-36770880-8a66-11eb-95f7-0c337f50fed1.png)

[스토어_v1.1.0.zip](https://github.com/hmterestingthinking/Honeybread/files/6177028/_v1.1.0.zip)
